
version: 2

models:
    - name: dbt_departments
      description: "A starter dbt model"
      columns:
          - name: dep_id
            description: "The primary key for department table"
            tests:
                - unique
                - not_null
          - name: dep_name
            description: "The department name"

    - name: dbt_jobs
      description: "A starter dbt model"
      columns:
          - name: job_id
            description: "The primary key for job table"
            tests:
                - unique
                - not_null
          - name: job_description
            description: "The job name"
